# read more
# https://octo.github.com/projects/repo-visualization
name: Create diagram
on:
  push:
    branches:
      - 'master'
jobs:
  create_diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          # https://github.com/githubocto/repo-visualizer
          excluded_paths: ".github,tests,docker,validation,gradle,config"
          max_depth: 15
          branch: 'repo-visualizer'
